// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwAcTjDre8tPTkOpVFEhWafYVS1dmul4',
    appId: '1:34964086966:web:aec289ad93521e907a0617',
    messagingSenderId: '34964086966',
    projectId: 'spp-online-44b6c',
    authDomain: 'spp-online-44b6c.firebaseapp.com',
    storageBucket: 'spp-online-44b6c.appspot.com',
    measurementId: 'G-J71ESFJ3L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlfz3jPOvD4nUCG0x6WZwRPANBvDT-rk',
    appId: '1:34964086966:android:b28457be75d4ce227a0617',
    messagingSenderId: '34964086966',
    projectId: 'spp-online-44b6c',
    storageBucket: 'spp-online-44b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCManx9tU_Ob-hIueuyz-jt4zs6sy16jeY',
    appId: '1:34964086966:ios:3a0a51b8554124237a0617',
    messagingSenderId: '34964086966',
    projectId: 'spp-online-44b6c',
    storageBucket: 'spp-online-44b6c.appspot.com',
    iosClientId: '34964086966-nq6uic4v82e0n7hp2v21cp90niqqtgj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiSpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCManx9tU_Ob-hIueuyz-jt4zs6sy16jeY',
    appId: '1:34964086966:ios:f4b8526a2ee19b667a0617',
    messagingSenderId: '34964086966',
    projectId: 'spp-online-44b6c',
    storageBucket: 'spp-online-44b6c.appspot.com',
    iosClientId: '34964086966-3ts0bk4m47q07uea97r1anobmappnjt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiSpp.RunnerTests',
  );
}
